Scoovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls')),
    path('', include('user.urls')),
    path('company/', include('company.urls')),
    path('employee/', include('employee.urls')),
]

company/urls.py
from django.urls import path
from .views import (
    company_dashboard,
    create_company_profile,
    company_shifts_and_job_reqs,
    crud_secret_code,
    run_ga,
    transmission_table,
)

app_name = 'company'

urlpatterns = [
    path('dashboard/', company_dashboard, name='home'),
    path('profile/create/', create_company_profile, name='create_profile'),
    path('data/', company_shifts_and_job_reqs, name='shift_and_jobreq'),
    path('generate-schedule/', run_ga, name='run_ga'),
    path('secret-code/', crud_secret_code, name='secret_code'),
    path('transmission-table/', transmission_table, name='transmission_table'),
]

user/urls.py
from django.urls import path
from .views import (
    signup_employee,
    signup_company,
    login_view,
    logout_view,
)

app_name = 'user'

urlpatterns = [
    path('signup/', signup_employee, name='signup_employee'),
    path('signup/company/', signup_company, name='signup_company'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

templates/form/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bubble.css' %}">
{% endblock %}

{% block content %}
<div class="center" style="min-height: 80vh;">
    <h2 style="text-align: center;">Login</h2>
    <form method="POST" action="{{ url }}" class="center">
        <div class="form-sm-container">
                {% csrf_token %}
                {{ form }}
                <div class="error">
                    {{ error }}
                </div>
        </div>
        <button type="submit" class="mybutton green" style="margin-top: 5vh;">
            Submit
        </button>
    </form>
</div>
{% endblock %}

templates/form/medical_history.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Medical History {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bubble.css' %}">
{% endblock %}

{% block content %}
<div class="layout flexend">
    <div class="form-container">
        <h2>Medical History Form</h2>
        <form method="POST" action="{{ url }}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="mybutton green" style="margin-top: 2vh;">
                Submit
            </button>
        </form>
    </div>
</div>
</div>
<div class="sticky-left">
    <div>
        <img src="{% static 'images/penguin_doctor.png'%}" alt="Penguin Doctor" class="penguin">
    </div>
    <div class="chat right">
        <div class="talk-bubble tri-right btm-left-in">
            <div class="talktext">
            <p>Please fill in the following medical history questionnaire.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/form/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Your Profile {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bubble.css' %}">
{% endblock %}

{% block content %}
<div class="layout flexend">
    <div class="form-container">
        <h2>
            {% if action == 'update' %}
                Update your Profile
            {% else %}
                Welcome, {{ user.get_full_name }}!
            {% endif %}
        </h2>
        <form method="POST" action="{{ url }}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="mybutton green" style="margin-top: 2vh;">
                {% if action == 'update' %}
                    Save
                {% else %}
                    Submit
                {% endif %}
            </button>
        </form>
        <p style="color: red; margin-top: 1.5rem; font-weight: 400;">{{ error }}</p>
    </div>
</div>
<div class="sticky-left">
    <div>
        <img src="{% static 'images/penguin_facing_right.png'%}" alt="Penguin showing form" class="penguin">
    </div>
    <div class="chat right">
        <div class="talk-bubble tri-right btm-left-in">
            <div class="talktext">
            {% if action == 'update' %}
                <p>What do you want to update?</p>
            {% else %}
                <p>Please complete your {{ type }} profile for our assessment.</p>
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/form/shift_and_jobreq.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Shifts and Job Requirements {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bubble.css' %}">
{% endblock %}

{% block content %}
<div class="layout">
    <form method="POST" action="{% url 'company:shift_and_jobreq' %}">
        {% csrf_token %}
        <div class="flexend" style="margin-bottom: 5vh;">
            <button type="submit" class="mybutton green" style="margin: 0;">
                Save
            </button>
        </div>
        <div class="wrap-container">
            <div class="form-sm-container">
                <div id="company_shift_form" data-shifts="{{ shifts }}">
                    <h2 style="margin-bottom: 1rem;">Work Shifts per Day</h2>
                    <p style="margin: 0 0 4vh;">
                        If there are no shifts, fill in the start and end operation time of your company.
                    </p>
                </div>
                <button type="button" class="btn green" id="add_shift" onClick="addShiftRow()">
                    + Add Shift
                </button>
            </div>

            <div class="form-container">
                <div id="company_jobreq_form" data-job-type-choices="{{ job_type_choices }}"
                    data-job-reqs="{{ job_reqs }}">
                    <h2 style="margin-bottom: 1rem;">Job Requirements per Shift</h2>
                    <p style="margin: 0;">
                        Current number of employees per shift:
                        <b>{{ employees_per_shift }}</b>
                    </p>
                    <p style="margin: 0 0 4vh;">
                        (will be overridden by the sum of employees in job requirements if they are filled)
                    </p>
                </div>
                <button type="button" class="btn green" id="add_shift" onClick="addJobReqRow()">
                    + Add Job Requirement
                </button>
            </div>
        </div>
    </form>
</div>

<script src="{% static 'javascript/shift_and_jobreq.js' %}"></script>
{% endblock %}

templates/form/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Sign Up {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bubble.css' %}">
{% endblock %}

{% block content %}
<div class="layout">
    <div class="form-container">
        <h2>Create your Scoovid Account</h2>
        <form method="POST" action="{{ url }}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="mybutton green" style="margin-top: 2vh;">
                Submit
            </button>
        </form>
    </div>
</div>
<div class="sticky-right">
    <div class="chat">
        <div class="talk-bubble tri-right btm-right-in">
            <div class="talktext">
            <p>Please fill in the {{ type }} registration form.</p>
            </div>
        </div>
    </div>
    <div>
        <img src="{% static 'images/penguin_show_left.png'%}" alt="Penguin showing form" class="penguin">
    </div>
</div>
{% endblock %}