Scoovid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls')),
    path('', include('user.urls')),
    path('company/', include('company.urls')),
    path('employee/', include('employee.urls')),
]

company/urls.py
from django.urls import path
from .views import (
    company_dashboard,
    create_company_profile,
    company_shifts_and_job_reqs,
    crud_secret_code,
    run_ga,
    transmission_table,
)

app_name = 'company'

urlpatterns = [
    path('dashboard/', company_dashboard, name='home'),
    path('profile/create/', create_company_profile, name='create_profile'),
    path('data/', company_shifts_and_job_reqs, name='shift_and_jobreq'),
    path('generate-schedule/', run_ga, name='run_ga'),
    path('secret-code/', crud_secret_code, name='secret_code'),
    path('transmission-table/', transmission_table, name='transmission_table'),
]

employee/urls.py
from django.urls import path
from .views import (
    employee_home,
    get_company_by_code,
    create_employee_profile,
    record_medical_history,
    view_company_schedule,
)

app_name = 'employee'

urlpatterns = [
    path('schedule/', employee_home, name='home'),
    path('company-schedule/', view_company_schedule, name='company_schedule'),
    path('profile/create/company/', get_company_by_code, name='get_company_by_code'),
    path('profile/create/', create_employee_profile, name='create_profile'),
    path('register/medical-history-data/', record_medical_history, name='medical_history_form'),
]

general/urls.py
from django.urls import path
from django.conf import settings
from .views import (
    landing_page,
)

app_name = 'home'

urlpatterns = [
    path('', landing_page, name='landing'),
]

if settings.DEBUG:
    urlpatterns += [
    ]

user/urls.py
from django.urls import path
from .views import (
    signup_employee,
    signup_company,
    login_view,
    logout_view,
)

app_name = 'user'

urlpatterns = [
    path('signup/', signup_employee, name='signup_employee'),
    path('signup/company/', signup_company, name='signup_company'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext_lazy as _
from constants.model_choices import UserType


def extract_username_from_email(email):
    return email.split('@')[0]


class CustomUserManager(UserManager):

    def create_user(self, username, email=None, password=None, **extra_fields):
        if not username:
            username = extract_username_from_email(email)
        return super().create_user(username, email, password, **extra_fields)

    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        if not username:
            username = extract_username_from_email(email)
        return super().create_superuser(username, email, password, **extra_fields)


class User(AbstractUser):
    username = models.CharField(
        _('username'),
        max_length=150,
        blank=True,
    )
    email = models.CharField(
        _('email'),
        max_length=255,
        unique=True,
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )
    type = models.IntegerField(choices=UserType.choices, default=UserType.EMPLOYEE)

    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

company/forms.py
from django.utils.translation import gettext_lazy as _
from django.forms import (
    ModelForm,
    CharField,
    EmailInput,
    NumberInput,
    TextInput,
    TimeInput,
    Select,
)
from constants.form_attrs import (
    default_attrs,
    time_attrs,
)
from user.models import User
from user.forms import SignupForm
from .models import Company


class CompanyProfileForm(ModelForm):
    class Meta:
        model = Company
        fields = [
            'industry',
            'employee_capacity',
            'employees_per_shift',
            'start_operation_day',
            'end_operation_day',
        ]
        widgets = {
            'industry': Select(attrs=default_attrs),
            'employee_capacity': NumberInput(attrs=default_attrs),
            'employees_per_shift': NumberInput(attrs=default_attrs),
            'start_operation_day': Select(attrs=default_attrs),
            'end_operation_day': Select(attrs=default_attrs),
        }
        labels = {
            'employees_per_shift': _('Number of employees per shift:'),
        }


class CompanySecretCodeForm(ModelForm):
    secret_code = CharField(
        label=_("Company's Secret Code:"),
        widget=TextInput(attrs=default_attrs),
        required=True,
    )

    class Meta:
        model = Company
        fields = ['secret_code']

employee/forms.py
from django.utils.translation import gettext_lazy as _
from django.forms import (
    ModelForm,
    DateInput,
    EmailInput,
    PasswordInput,
    TextInput,
    RadioSelect,
    Select,
    Form,
    ChoiceField,
    CharField,
)
from constants.form_attrs import (
    default_attrs,
    dob_attrs,
    radioselect_attrs,
)
from constants.form_choices import (
    yes_or_no_choices,
)
from .models import Employee


class EmployeeProfileForm(ModelForm):
    company_name = CharField(
        label=_("Company:"),
        widget=TextInput(attrs=default_attrs),
        disabled=True,
        required=False,
    )

    class Meta:
        model = Employee
        fields = [
            'company_name',
            'date_of_birth',
            'job_type',
        ]
        widgets = {
            'date_of_birth': DateInput(attrs=dob_attrs),
            'job_type': Select(attrs=default_attrs),
        }
        
    def __init__(self, *args, **kwargs):
        job_type_choices = []
        if 'job_type_choices' in kwargs:
            job_type_choices = kwargs.pop('job_type_choices')
        super(EmployeeProfileForm, self).__init__(*args, **kwargs)
        self.fields['job_type'].choices = job_type_choices


class MedicalHistoryForm(Form):
    cardiovascular = ChoiceField(label = 'Cardiovascular Disease?', widget = RadioSelect(attrs=radioselect_attrs), choices = yes_or_no_choices, initial=False)
    diabetes = ChoiceField(label = 'Diabetes?', widget = RadioSelect(attrs=radioselect_attrs), choices = yes_or_no_choices, initial=False)
    chronic_respiratory = ChoiceField(label = 'Chronic Respiratory?', widget = RadioSelect(attrs=radioselect_attrs), choices = yes_or_no_choices, initial=False)
    hypertension = ChoiceField(label = 'Hypertension?', widget = RadioSelect(attrs=radioselect_attrs), choices = yes_or_no_choices, initial=False)
    cancer = ChoiceField(label = 'Cancer?', widget = RadioSelect(attrs=radioselect_attrs), choices = yes_or_no_choices, initial=False)

company/views.py
from django.shortcuts import render, redirect, reverse
from django.db.models import Prefetch
from datetime import time
from .forms import CompanyProfileForm
from .models import Company, JobRequirement, Shift

from ai import run_genetic_algorithm
from employee.models import Employee, EmployeeShift
from general.models import JobType
from user.models import User
from user.permissions import company_required
from utils.company import (
    clean_shift_input,
    clean_jobreq_input,
    generate_secret_code,
)


def get_company(user):
    return Company.objects.prefetch_related(
        'shift_set',
        'employee_set',
        'jobrequirement_set',
    ).get(user_id=user.id)


@company_required()
def run_ga(request):
    company = get_company(request.user)
    queryset = company.shift_set.prefetch_related('employeeshift_set').all()
    for shift in queryset: #deleting the already generated schedule if exist
        shift.employeeshift_set.all().delete()

    if company.employee_set.exists():
        run_genetic_algorithm(company)
    return redirect('company:home')


@company_required()
def company_dashboard(request):
    company = get_company(request.user)
    return get_company_schedule(request, company)


def get_company_schedule(request, company):
    raw_shifts = company.shift_set.prefetch_related('employeeshift_set').all()
    processed_shifts = convert_shift_array(raw_shifts)
    employees = company.employee_set.all()
    shift_sample = Shift.objects.filter(company=company,day=company.start_operation_day)
    return render(request, 'dashboard/dashboard.html', {
        'shifts':processed_shifts[0], 
        'employees':employees, 
        'shift_sample': shift_sample,
        'is_empty':processed_shifts[1],
        'schedule': 'company',
    })


def convert_shift_array(shifts):
    result = {}
    is_empty = True
    active_day = set()
    for shift in shifts:
        if (shift.day-1) not in active_day :
            result[shift.day-1] = {}
        current_employee_shift = shift.employeeshift_set.all()
        result[shift.day-1][shift] = current_employee_shift
        if len(current_employee_shift) >= 1:
            is_empty = False
        active_day.add(shift.day-1)
    return [result, is_empty]


@company_required()
def create_company_profile(request):
    form = CompanyProfileForm()
    if request.method == 'POST':
        form = CompanyProfileForm(request.POST)
        if form.is_valid():
            company = form.save()
            company.user = request.user
            company.secret_code = generate_secret_code(company.id)
            company.save()
            return redirect('company:shift_and_jobreq')

    return render(request, 'form/profile.html', {
        'action': 'create',
        'url': reverse('company:create_profile'),
        'form': form,
    })


@company_required()
def company_shifts_and_job_reqs(request):
    company = get_company(request.user)

    if request.method == 'POST':
        data = request.POST
        shifts = clean_shift_input(data, company)
        company.shift_set.all().delete()
        Shift.objects.bulk_create(shifts)

        job_requirements = clean_jobreq_input(data, company)
        company.jobrequirement_set.all().delete()
        JobRequirement.objects.bulk_create(job_requirements)

        if len(job_requirements) > 0:
            company.employees_per_shift = sum([j.num_of_employee for j in job_requirements])
            company.save()
        return redirect('company:home')
    else:
        job_types = JobType.objects.filter(industry_id=company.industry_id)
        job_type_choices = [{'id': j.id, 'name': j.name} for j in job_types]

        company_shifts = set()
        for s in company.shift_set.all():
            company_shifts.add((s.start_time.hour, s.end_time.hour))
        company_shifts = [
            {'start_time': start, 'end_time': end}
            for start, end in sorted(company_shifts)
        ]

        company_job_reqs = [
            {'job_type_id': j.job_type_id, 'num_of_employee': j.num_of_employee} 
            for j in company.jobrequirement_set.all()
        ]

    return render(request, 'form/shift_and_jobreq.html', {
        'url': reverse('company:shift_and_jobreq'),
        'job_type_choices': job_type_choices,
        'shifts': company_shifts,
        'job_reqs': company_job_reqs,
        'employees_per_shift': company.employees_per_shift,
    })


@company_required()
def crud_secret_code(request):
    company = request.user.company
    if not company.secret_code:
        company.secret_code = generate_secret_code(company.id)
        company.save()

    return render(request, 'company_secret_code.html', {
        'company': company
    })


@company_required()
def transmission_table(request):
    company = get_company(request.user)
    raw_shifts = company.shift_set.prefetch_related('employeeshift_set').all()
    processed_shifts = convert_shift_array_for_transmission_table(raw_shifts)
    employees = company.employee_set.all()
    return render(request, 'company_transmission_table.html', {
        'shifts':processed_shifts[0], 
        'employees':employees, 
        'is_empty': processed_shifts[1],
        'shift_sample': raw_shifts,
    })

def convert_shift_array_for_transmission_table(raw_shifts):
    result = []
    is_empty = True
    for raw_shift in raw_shifts:
        tmp = {}
        current_employee_shift = raw_shift.employeeshift_set.all()
        tmp[raw_shift] = current_employee_shift
        if len(current_employee_shift) >= 1:
            is_empty = False
        result.append(tmp)

    return [result, is_empty]

employee/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from .forms import EmployeeProfileForm, MedicalHistoryForm
from .models import MedicalHistory, Employee, EmployeeShift

from company.models import Company
from company.forms import CompanySecretCodeForm
from company.views import get_company_schedule
from general.models import JobType
from user.models import User
from user.permissions import employee_required
from utils.calculate_medical_risk import (
    calculate_age_risk,
    calculate_disease_risk,
)
from utils.clean_medical_history_input import (
    clean_medical_history_input,
)


@employee_required()
def view_company_schedule(request):
    company = request.user.employee.company
    return get_company_schedule(request, company)


@employee_required()
def employee_home(request):
    employee = request.user.employee
    employee_shift = EmployeeShift.objects.filter(employee=employee)
    converted_shifts = convert_shift_array(employee_shift)
    return render(request, 'dashboard/dashboard.html', {
        'shifts':converted_shifts, 
        'schedule': 'employee',
        'employee':employee
    })


def convert_shift_array(employee_shift):
    result = {}
    active_shift = set()
    for i in employee_shift:
        if (i.shift.day-1) not in active_shift :
            result[i.shift.day-1] = []
        result[i.shift.day-1].append(str(i.shift))
        active_shift.add(i.shift.day-1)
    return result


@employee_required()
def get_company_by_code(request):
    if hasattr(request.user, 'employee'):
        return redirect('employee:home')

    context = {
        'action': 'create',
        'url': reverse('employee:get_company_by_code'),
        'form': CompanySecretCodeForm,
    }

    if request.method == 'POST':
        try:
            company = Company.objects.get(secret_code=request.POST['secret_code'])
            employee = Employee.objects.create(
                company=company,
                user=request.user,
            )
            return redirect('employee:create_profile')
        except Company.DoesNotExist:
            context['error'] = 'Company does not exist. Please re-check the secret code with your company.'
    return render(request, 'form/profile.html', context)


@employee_required()
def create_employee_profile(request):
    employee = request.user.employee

    if request.method == 'POST':
        form = EmployeeProfileForm(request.POST)
        if form.is_valid():
            employee.date_of_birth = request.POST['date_of_birth']
            employee.job_type_id = request.POST['job_type']
            employee.save()
            return redirect('employee:medical_history_form')
    else:
        company = employee.company
        job_types = JobType.objects.filter(industry_id=company.industry_id)
        job_type_choices = [(j.id, j.name) for j in job_types]

        form = EmployeeProfileForm(
            initial={'company_name': company.name},
            job_type_choices=job_type_choices,
        )

    return render(request, 'form/profile.html', {
        'action': 'create',
        'url': reverse('employee:create_profile'),
        'form': form,
    })


@employee_required()
def record_medical_history(request):
    form = MedicalHistoryForm()
    employee = request.user.employee

    if request.method == 'POST':
        form = MedicalHistoryForm(request.POST)
        if form.is_valid():
            medical_history = MedicalHistory()
            cleaned_input = clean_medical_history_input(request.POST)
            medical_history.cardiovascular = calculate_disease_risk(cleaned_input, 'cardiovascular')
            medical_history.diabetes = calculate_disease_risk(cleaned_input, 'diabetes')
            medical_history.chronic_respiratory = calculate_disease_risk(cleaned_input, 'chronic_respiratory')
            medical_history.hypertension = calculate_disease_risk(cleaned_input, 'hypertension')
            medical_history.cancer = calculate_disease_risk(cleaned_input, 'cancer')
            medical_history.age_risk = calculate_age_risk(employee.age)
            medical_history.employee = employee
            medical_history.save()
            return redirect('employee:home')

    return render(request, 'form/medical_history.html', {
        'url': reverse('employee:medical_history_form'),
        'form': form,
    })

templates/navbar/company.html
{% load static %}
<script src="{% static 'javascript/navbar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav>
	<a class="logo_mobile" href="{% url 'home:landing' %}">
		<img src="{% static 'images/logo.png' %}" height="30px" alt="Scoovid">
	</a>
	<div class="navi">
		<div class="hamburger">
			<img class="dropdown" src="{% static 'images/dropdown.svg' %}" height="15px" alt="Dropdown">
		</div>
		<div class="nav-layout" style="height: 100%;">
			<div class="row" style="height: inherit;">
				<div class="col-3 onlypc">
					<a class="logo_pc" href="{% url 'home:landing' %}">
						<img height="40px" src="{% static 'images/logo.png' %}" alt="Scoovid">
					</a>
				</div>
				<div class="col" style="padding-right: 15px;">
					<ul class="nav-links">
						<li><a href="{% url 'company:home' %}">
							Dashboard
						</a></li>
						<li><a href="{% url 'company:transmission_table' %}">
							Transmission table
						</a></li>
						<li><a href="{% url 'company:secret_code' %}">
							Secret Code
						</a></li>
						<li><a href="{% url 'company:shift_and_jobreq' %}">
							Shifts and Job Requirements
						</a></li>
						<div class="onlypc" style="width: 15px;"></div>
						<li><a href="{% url 'company:run_ga' %}" class="mybutton green">
							Generate New Schedule
						</a></li>
						<div class="onlypc" style="width: 15px;"></div>
						<li>
							<form action="{% url 'user:logout' %}" method="POST">
								{% csrf_token %}
								<button style="border: none;outline:none;" type="submit"><a class="mybutton green">
									Log Out
								</a></button>
							</form>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>

templates/navbar/default.html
{% load static %}
<script src="{% static 'javascript/navbar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav>
	<a class="logo_mobile" href="{% url 'home:landing' %}">
		<img src="{% static 'images/logo.png' %}" height="30px" alt="Scoovid">
	</a>
	<div class="navi">
		<div class="hamburger">
			<img class="dropdown" src="{% static 'images/dropdown.svg' %}" height="15px" alt="Dropdown">
		</div>
		<div class="nav-layout" style="height: 100%;">
			<div class="row" style="height: inherit;">
				<div class="col-3 onlypc">
					<a class="logo_pc" href="{% url 'home:landing' %}">
						<img height="40px" src="{% static 'images/logo.png' %}" alt="Scoovid">
					</a>
				</div>
				<div class="col" style="padding-right: 15px;">
					<ul class="nav-links">
						<div class="onlypc" style="width: 15px;"></div>
						<li>
							<a href="{% url 'user:login' %}" class="mybutton green">Sign In</a>
						</li>
						<div class="onlypc" style="width: 15px;"></div>
						<li>
							<a onclick="overlayon('upload_foreground_sign_up')" class="mybutton green">Sign Up</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>

templates/navbar/employee.html
{% load static %}
<script src="{% static 'javascript/navbar.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav>
	<a class="logo_mobile" href="{% url 'home:landing' %}">
		<img src="{% static 'images/logo.png' %}" height="30px" alt="Scoovid">
	</a>
	<div class="navi">
		<div class="hamburger">
			<img class="dropdown" src="{% static 'images/dropdown.svg' %}" height="15px" alt="Dropdown">
		</div>
		<div class="nav-layout" style="height: 100%;">
			<div class="row" style="height: inherit;">
				<div class="col-3 onlypc">
					<a class="logo_pc" href="{% url 'home:landing' %}">
						<img height="40px" src="{% static 'images/logo.png' %}" alt="Scoovid">
					</a>
				</div>
				<div class="col" style="padding-right: 15px;">
					<ul class="nav-links">
						<li><a href="{% url 'employee:company_schedule' %}">
							Company Schedule
						</a></li>
						<li><a href="{% url 'employee:home' %}">
							My Schedule
						</a></li>
						<div class="onlypc" style="width: 15px;"></div>
						<li>
							<form action="{% url 'user:logout' %}" method="POST">
								{% csrf_token %}
								<button style="border: none;outline:none;" type="submit"><a class="mybutton green">
									Log Out
								</a></button>
							</form>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>

templates/navbar/index.html
{% if user.get_type_display == 'company' %}
    {% include './company.html' %}
{% elif user.get_type_display == 'employee' %}
    {% include './employee.html' %}
{% else %}
    {% include './overlay_sign_up.html' %}
    {% include './default.html' %}
{% endif %}

templates/navbar/overlay_sign_up.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/overlay.css' %}">
<link rel="stylesheet" href="{% static 'css/box.css' %}">
<div class="fore overlay_foreground daftar_fore" id="upload_foreground_sign_up">
    <h2 style="margin-left: 15px;">Sign Up</h2>
    <div class="container">
        <div class="row">
            <div class="col-md" style="margin-bottom: 30px;">
                <a href="{% url 'user:signup_employee' %}">
                    <div style="min-height: 120px;" class="box employee">
                        <p class="bold box_title">Employee</p>
                    </div>
                </a>
            </div>
            <div class="col-md" style="margin-bottom: 30px;">
                <a href="{% url 'user:signup_company' %}">
                    <div style="min-height: 120px;" class="box company">
                        <p class="bold box_title">Company</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="overlay" id="overlay" onclick="off()">
</div>